#!/bin/bash

## X server log and authentication file
xslog='/etc/X11/glm/log/xserver.log'
xsauth='/etc/X11/glm/log/glm.auth'


## Environment variables passed in by GLM
display="$1"
tty=`echo "$2" | sed 's/tty//'`


## Start the X server
/usr/bin/Xorg -nolisten tcp "$display" -auth "$xsauth" "vt$tty" &> "$xslog" &

## Start the X compositing manager (for transparency)
while true; do
    scheck=`grep -c 'Using system config' "$xslog"`
    if [ $scheck -eq 1 ]; then
        /usr/bin/xcompmgr &
        break
    fi
done


## Set background 
/usr/bin/hsetroot -fill /etc/X11/glm/img/wallpapers/night-sky.jpg

## Cursor and background attributes
/usr/bin/xsetroot -cursor_name left_ptr
